### ISSUE TITLE
contenthash used for direct access to files

### ISSUE THREAD

**Issue by danmarsden** [Copyleaks/moodle-plagiarism_copyleaks#10]
https://github.com/Copyleaks/moodle-plagiarism-checker/blob/b0cff9a6a21a648776cd0de5cec113f5e48e7601/scan.php#L51

that file seems to allow for any contenthash to be passed and sent to the external service - this seems like a security issue to me. A user could arbitrarily guess contenthashes - or find a method of obtaining a contenthash for a file they don't have access to and have it sent to copyleaks and get access to it there.

You should really be using Moodle File api functions to access files and pass them rather than accessing them directly on disk based on the content hash.

**Comment by danmarsden** [comment]
definitely a security issue there. your use of plagiarism_copyleaks_file_hash_name_to_path is vulnerable to a path traversal attack. You should significantly rewrite the way you access the files and pass them to copyleaks.

**Comment by danmarsden** [comment]
This is still an issue in your code - how have you addressed this issue? - When you do resolve this it would be good if you could add a comment pointing to a commit that addresses this.

**Comment by elir-copyleaks** [comment]
Hi @danmarsden. We have removed the usage of contenthash in commit b2a97b2c1acabe85074209299ea1701653bfe36d. Have I missed something. I did a search for contenthash in the code with 0 results. Thanks, Eli.

**Comment by danmarsden** [comment]
You have not understood the reported issue. Scan.php uses the file hash instead of the moodle file api and is vulnerable to directory transversal attacks. Unfortunately the plugin review team is unable to provide mentoring support to help developers fix the issues reported. If you are unable to resolve this yourself you could ask for help in the moodle community forums or you could consider contracting your local moodle partner to help review and fix your code. Good luck!

**Comment by elir-copyleaks** [comment]
Hi @danmarsden,
We:
1. get the $file object passed to our plugin lib.
2.  We pass the $file pathnamehash property to the Scan.php.
3. We then continue using the moodle file api to get the file content. 

Which part of this process chain is not acceptable? Is there another way to share files between pages? 

I'll ask this in the moodle community forums too.
Thanks in advance, Eli.
