### ISSUE TITLE
Error accented characters in french

### ISSUE THREAD

**Issue by aurelienb1** [Copyleaks/moodle-plagiarism_copyleaks#12]
Hi

There is an encoding error for accented characters in french when I look at the answers in a quiz. See the screenshot.

See picture [https://udemontreal-my.sharepoint.com/:i:/g/personal/aurelien_besson_umontreal_ca/EW5fVpVq2HRHnyk-_IdzWbMB3zzXJk2cP15gvqit7nZnKQ?e=RYi9vv](url)

**Comment by eladbitton** [comment]
Hi!
Can you provide a scan id or the exact text/document that you have scanned?

**Comment by aurelienb1** [comment]
Hi,

I have made a copy paste, from quiz to quiz.

I make another test, and i come back to you.

Reagrds,

Aurélien Besson | Concepteur TI
TI - Portefeuille technopédagogique | Université de Montréal

De : eladbitton ***@***.***>
Envoyé : 26 juillet 2022 02:25
À : Copyleaks/moodle-plagiarism_copyleaks ***@***.***>
Cc : Aurélien Besson ***@***.***>; Author ***@***.***>
Objet : Re: [Copyleaks/moodle-plagiarism_copyleaks] Error accented characters in french (Issue #12)

AVIS: Ce courriel provient de l'extérieur de l'Université de Montréal. Veuillez ne pas cliquer sur les liens ni ouvrir les fichiers joints si vous n'êtes pas certain(e) de la légitimité du courriel.


Hi!
Can you provide a scan id or the exact text/document that you have scanned?

-
