### ISSUE TITLE
Choice of colors and web  accessibility 

### ISSUE THREAD

**Issue by aurelienb1** [Copyleaks/moodle-plagiarism_copyleaks#13]
Hi,

Choice of colors, for better inclusion we should review the choice of colors or offer an option for people who are color blind.

Another point, we must also take into account users with disabilities and make the plugin as web  Accessibility as possible.

Regards

**Comment by CL-BayanAbuawad** [comment]
@aurelienb1, the design was changed for these parts - please reopen if you still see this issue on the newer versions.
