### ISSUE TITLE
Wrong column XML type 

### ISSUE THREAD

**Issue by Arvaloez** [Copyleaks/moodle-plagiarism_copyleaks#45]
Hello,
I'm integrating the last version of Copyleaks and I got the following error:

plagiarism_copyleaks_files
 * column 'retrycnt' has incorrect type 'N', expected 'I'

The possible solution is to change on the upgrade file, line 472, the XMLDB_TYPE_NUMBER to XMLDB_TYPE_INTEGER.

Could you help us with this change?

Thank you.

**Comment by CL-BayanAbuawad** [comment]
@Arvaloez thank you for reporting this; a fix was applied here and merged [here](https://github.com/Copyleaks/moodle-plagiarism_copyleaks/pull/46)

A new version was deployed to the Moodle marketplace:
https://moodle.org/plugins/plagiarism_copyleaks

**Comment by Arvaloez** [comment]
Hi @CL-BayanAbuawad,

Firstly, thank you for addressing the issue. Your assistance is greatly appreciated.

While most aspects seem to be functioning correctly now, there's still an issue persisting. It appears that when you altered the field type, you overlooked the necessity of adjusting the default option for null values. It's imperative to set the field default to '0' after the type change.

Upon integration, we received the following response:

plagiarism_copyleaks_files
* column 'retrycnt' has default 'NULL', expected '0' (I)

To rectify this, on the upgrade file, at line 471, requires an amendment. The default parameter must be set to '0'.

Once again, thank you for your invaluable support.

**Comment by CL-BayanAbuawad** [comment]
@Arvaloez Thank you! We missed this somehow. We are not getting this issue on our side, and we are working on understanding why.

A fix was applied to the new issue [here](https://github.com/Copyleaks/moodle-plagiarism_copyleaks/pull/46)

A new version was deployed to the Moodle marketplace:
https://moodle.org/plugins/plagiarism_copyleaks

**Comment by Arvaloez** [comment]
Hi @CL-BayanAbuawad, Thank you for your support. I'm in the process of uploading the changes. Once I have the results, I'll be sure to provide you with an update.

It appears that the issue is related to the DB manager. While I've achieved successful results with PostgreSQL, is with MySQL when I got this issue. Perhaps this info could help you to find the issue. Thank you again for your help.
