### ISSUE TITLE
Missing string identifiers

### ISSUE THREAD

**Issue by farhan6318** [Copyleaks/moodle-plagiarism_copyleaks#52]
Running the full moodle test suite with this plugin throws some errors about missing string identifiers

1. Debugging: Invalid get_string() identifier: 'copyleaks:viewfullreport' or component 'plagiarism_copyleaks'. Perhaps you are missing $string['copyleaks:viewfullreport'] = ''; in /builds/open-lms/product/work/moodle/plagiarism/copyleaks/lang/en/plagiarism_copyleaks.php?

2. Debugging: Invalid get_string() identifier: 'copyleaks:enable' or component 'plagiarism_copyleaks'. Perhaps you are missing $string['copyleaks:enable'] = ''; in /builds/open-lms/product/work/moodle/plagiarism/copyleaks/lang/en/plagiarism_copyleaks.php?

**Comment by CL-BayanAbuawad** [comment]
@farhan6318, thanks for reporting this - we will add a fix for this in our next release.

**Comment by CL-BayanAbuawad** [comment]
@farhan6318 A fix has been deployed for this issue.
