### ISSUE TITLE
hard coded db prefix

### ISSUE THREAD

**Issue by danmarsden** [Copyleaks/moodle-plagiarism_copyleaks#8]
https://github.com/Copyleaks/moodle-plagiarism-checker/blob/master/copyleaks_stats.php#L90

mdl_ is the default prefix but many sites modify this so you should be wrapping the table name in curly braces. - please review all your code to ensure you have not hard-coded the mdl_ prefix.

**Comment by elir-copyleaks** [comment]
ddbe2d318fa174bf2488351281f522ac327207a1 fixes this.
